import { Montserrat } from 'next/font/google'
import { Footer } from './components/shared/Footer'
import { LandingHeader } from './components/landingPage/LandingHeader'
import { Header } from './components/shared/Header'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'
import './globals.css'
import { UserProvider } from '@/providers/UserProvider'
import { SessionProvider } from '@/providers/SessionProvider'
const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout ({ children }) {
  const session = await getServerSession(authOptions)
  return (
    <html lang='es' className='scroll-smooth'>
      <body
        className={`${montserrat.className} antialiased bg-primary-bg dark:bg-dark-primary-bg selection:bg-primary-accent dark:selection:bg-dark-primary-accent selection:text-white`}
      >
        <UserProvider user={session?.user}>
          {session ? <Header /> : <LandingHeader />}
          <SessionProvider session={session}>
            {children}
          </SessionProvider>
        </UserProvider>
        <Footer rol={session?.user?.idRol} />
      </body>
    </html>
  )
}
